product_types: 3
turn_no: 500
break_time: 5
breaking_chance: 5
change_time: 4
orders:
  one_type: True
  max_value: 3
  min_reward: 3
  max_reward: 10
  min_penalty: 0
  max_penalty: 10
  min_due_time: 10
  max_due_time: 40
  #same_value: 1
logging:
  path: 'logs/flowshop.log'
  format: '%(asctime)s %(message)s'
layers:
  - machines:
    - time_table:
        1: 2
        2: 1
        3: 3
    - time_table:
        1: 2
        2: 1
        3: 3
    - time_table:
        1: 2
        2: 1
        3: 3
  - machines:
    - time_table:
        1: 2
        2: 1
        3: 3
  - machines:
    - time_table:
        1: 2
        2: 1
        3: 3
    - time_table:
        1: 2
        2: 1
        3: 3