orders:
  one_type: True
  max_value: 3
  min_reward: 3
  max_reward: 10
  min_penalty: 0
  max_penalty: 10
  min_due_time: 10
  max_due_time: 40
  #same_value: 1
logging:
  path: '../logs/flowshop.log'
  format: '%(asctime)s %(message)s'
product_types: 3